# Generated by Django 4.2.5 on 2023-10-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_parametro', models.IntegerField(default=0)),
                ('con_problema', models.CharField(max_length=1)),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroError',
            fields=[
                ('correlativo', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('codigoError', models.CharField(default=1, max_length=100)),
                ('mensajeError', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('informe', models.FileField(upload_to='reportes')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.comuna', verbose_name='Comuna')),
                ('fkEstadoVisita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.estadovisita')),
                ('fkFormularioVisita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.formulariovisita')),
                ('fkProfesional', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional_visita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.CharField(max_length=1)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('nro_telefono', models.CharField(max_length=20)),
                ('disponibilidad', models.BooleanField()),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.comuna', verbose_name='Comuna')),
                ('fkUser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profesional_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fkVisita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asesora.visita')),
            ],
        ),
        migrations.CreateModel(
            name='IdxUsr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkUser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fkUsuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asesora.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimento', models.DateField()),
                ('total_factura', models.DateField()),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('fkEstadoFactura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.estadofactura')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.factura')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_cumple', models.CharField(max_length=1)),
                ('fkElementoRevision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.elementorevision')),
                ('fkFormularioVisita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.formulariovisita')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_termino', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('costo_mensual', models.IntegerField()),
                ('costo_modificacion_formulario', models.IntegerField()),
                ('costo_capacitacion_extra', models.IntegerField()),
                ('costo_asesoria_extra', models.IntegerField()),
                ('costo_llamada_extra', models.IntegerField()),
                ('costo_actualizar_informe', models.IntegerField()),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.region'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.CharField(max_length=1)),
                ('razon_legal', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.comuna', verbose_name='Comuna')),
                ('fkEstadoServicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.estadoservicio', verbose_name='EstadoServicio')),
                ('fkUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cant_asistente', models.IntegerField()),
                ('lista_asist', models.JSONField(null=True)),
                ('fecha_capacitacion', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.comuna', verbose_name='Comuna')),
                ('fkEstadoCapacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.estadocapacitacion')),
                ('fkProfesional', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_fiscalizador', models.CharField(max_length=200)),
                ('numero_fiscalizador', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('estado_asesoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estado_asesoria', to='asesora.estadoasesoria')),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('fkProfesional', models.ForeignKey(blank=True, default='Sin Asignar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional_asignado', to=settings.AUTH_USER_MODEL)),
                ('tipo_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_asesoria', to='asesora.tipoasesoria')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.CharField(max_length=1)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('nro_telefono', models.CharField(max_length=20)),
                ('disponibilidad', models.BooleanField()),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.comuna', verbose_name='Comuna')),
                ('fkUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accidente', models.DateField()),
                ('cantidad_involucrados', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('tipo_accidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesora.tipoaccidente')),
            ],
        ),
    ]
