# Generated by Django 4.2.5 on 2023-10-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asesora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='fkProfesional',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
