# Generated by Django 4.2.5 on 2023-10-22 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asesora', '0002_alter_asesoria_fkprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fkTipoEmpresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_empresa', to='asesora.tipoempresa', verbose_name='TipoEmpresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='fkCliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente_vista'),
        ),
    ]
