# Generated by Django 4.2.5 on 2023-10-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('asesora', '0004_alter_contrato_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank='True', related_name='usuarios_permisos', to='auth.permission', verbose_name='Permisos de usuario'),
        ),
    ]
