# Generated by Django 4.2.5 on 2023-10-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0005_alter_usuario_options_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='auth_group',
        ),
    ]
