# Generated by Django 4.2.5 on 2023-10-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0008_alter_usuario_date_joined_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdxUsr',
        ),
    ]
