# Generated by Django 4.2.5 on 2023-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0010_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
