# Generated by Django 4.2.5 on 2023-10-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0011_factura_pagada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fkEstadoFactura',
        ),
        migrations.DeleteModel(
            name='EstadoFactura',
        ),
    ]
