# Generated by Django 4.2.5 on 2023-11-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0012_remove_factura_fkestadofactura_delete_estadofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detalleformulario',
            name='fkElementoRevision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementorevision', to='asesora.elementorevision'),
        ),
        migrations.AlterField(
            model_name='detalleformulario',
            name='fkFormularioVisita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='asesora.formulariovisita'),
        ),
    ]
