# Generated by Django 4.2.5 on 2023-11-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0013_alter_asesoria_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='pagada',
            new_name='pagada_con_paypal',
        ),
        migrations.AddField(
            model_name='factura',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
