# Generated by Django 4.2.5 on 2023-12-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0014_rename_pagada_factura_pagada_con_paypal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pagada_con_paypal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='paypal_id',
        ),
    ]
