# Generated by Django 4.2.5 on 2023-12-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesora', '0015_remove_factura_pagada_con_paypal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
